---
title: "Plot time series"
author: "Leobardo Enriquez"
date: '2022-05-30'
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("reshape2") 
library("ggplot2")
library("lubridate")
library("dplyr")
```

## Summarizing data. 

We have information related to crude oil prices and forecast with lower and upper scenarios. 



```{r, echo=FALSE, warning=FALSE}
bd<-read.csv("C:/Users/Leobardo/Documents/GitHub/TimeSeries/oil.csv")
sum<-(summary(bd))
sum

```

## Including Plots

We can observe that the international oil price have a increasing behavior since many months ago.  

```{r pressure, echo=FALSE, warning=FALSE}
plot(bd$Price,  type="line", col="blue", lwd = 1, main="Oil price", xlab="Time", ylab="Price (Dollars)")
```

The next graph show the different scenarios for oil price. 


```{r, echo=FALSE, warning=FALSE}
bd<-as.data.frame(bd)
bd$time <- ts(bd$Month, start=c(2017, 1), end=c(2023, 12), frequency=12)
bd$time<-as.numeric(time(bd$time)) 
ggplot(bd,aes(x=time, y=Price))+
  geom_line(aes(x=time, y=Price),color="blue")+
  geom_point(aes(x=time, y=Price.1),color="green")+
  geom_point(aes(x=time, y=Forecast),color="red")+
  geom_point(aes(x=time, y=Lower),color="yellow")+
  geom_point(aes(x=time, y=Upper),color="purple")

```

